# All tables created in my-sql in reverse file order.
DROP TABLE IF EXISTS portfolio_posts;
DROP TABLE IF EXISTS project_post_comments;
DROP TABLE IF EXISTS portfolios;
DROP TABLE IF EXISTS project_posts;
DROP TABLE IF EXISTS project_cycles;
DROP TABLE IF EXISTS knowledge_and_skills;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS classes_teachers;
DROP TABLE IF EXISTS classes_students;
DROP TABLE IF EXISTS assignments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS teachers_schools;
DROP TABLE IF EXISTS classes;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS schools;
DROP TABLE IF EXISTS districts;
